name=FastStepper
version=1.0.0
author=Tarquinio Mota <tarquinio@gmail.com>
maintainer=Tarquinio Mota <tarquinio@gmail.com>
sentence=A software to control speed and acceleration in stepper motors.<br />
paragraph=This library produces control pulses for stepper motors on selected pwm capable pins.<br /> Multiple steppers can be controlled, depending of the atmega chip being used<br />It supports accurate step counting and endstops calibration<br /><br />Issues or questions: <a href="https://github.com/nightswimmer/FastStepper/issues"> />
category=Signal Input/Output
url=https://github.com/nightswimmer/FastStepper
architectures=avr
